image: ubuntu

before_script:
    - apt-get update -qy
    - apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh

stages:
    - production

production:
    stage: production
#    image: node:8.16.2-alpine
    script:
        - flyctl deploy
    only:
        - master

cache:
  paths:
  - node_modules/
