image: node:8.16.2-alpine

before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh

stages:
    - production

production:
    stage: production
    script:
        - flyctl deploy
    only:
        - master

cache:
  paths:
  - node_modules/
