production:
  type: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=nk-tree-client --api-key=$HEROKU_API_KEY
  only:
    - master
