name: CI/CD - Deploy to Fly

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: node:10.9-alpine3.15

    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 10.9

      - run: npm ci

#      - run: npm run lint
#
#      - run: npm test
#
#      - run: npm audit

      - name: Setup Fly.io config
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --no-cache

